services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    container_name: btalents
    restart: always
    ports:
      - "3005:3000"
    env_file:
      - .env.production
    extra_hosts:
      - "host.docker.internal:host-gateway" # permet d'accéder à MySQL sur - le host de docker
    command: >
      sh -c "pnpm prisma migrate deploy && node server.js"
