services:
  nextjs:
    container_name: btalents
    restart: always
    # On charge tout le fichier ici
    env_file:
      - .env.production
    build:
      context: .
      dockerfile: Dockerfile
      # Si ton Dockerfile a vraiment besoin de DATABASE_URL pendant le build (npm run build)
      # garde cette ligne, sinon tu peux l'enlever pour simplifier.
      args:
        - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3005:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      sh -c "pnpm prisma migrate deploy && node server.js"
